on: [push]
jobs:
  Run-Pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install .[dev]
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest test_kerchunk_netcdf4.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html